"""Small, shared helpers for rendering DEQ types and documents."""

from __future__ import annotations

from .types import PauliProduct


GENERATED_HEADER = "# Generated by tools/generate_rotated_surface_code_deq.py; do not edit by hand."


def validate_distance(distance: int) -> None:
    """Require a supported odd code distance."""
    if distance < 3 or distance % 2 == 0:
        raise ValueError("distance must be odd and at least 3")


def product(pauli: str, qubits: tuple[int, ...]) -> str:
    """Render a same-basis Pauli product."""
    return "*".join(f"{pauli}{qubit}" for qubit in qubits)


def targets(qubits: range | list[int] | tuple[int, ...]) -> str:
    """Render DEQ/Stim target IDs separated by spaces."""
    return " ".join(map(str, qubits))


def products_text(products: list[PauliProduct]) -> str:
    """Render a space-separated list of CSS stabilizers."""
    return " ".join(product(pauli, qubits) for pauli, qubits in products)


def indent(lines: list[str], spaces: int = 4) -> str:
    """Render generated circuit lines at the body indentation level."""
    prefix = " " * spaces
    return "\n".join(prefix + line for line in lines)


def document(*sections: str) -> str:
    """Join non-empty DEQ sections with one blank line and a final newline."""
    return "\n\n".join(section.strip() for section in sections if section.strip()) + "\n"


def generated_document(*sections: str) -> str:
    """Return a generated DEQ file with the standard provenance header."""
    return document(GENERATED_HEADER, *sections)


def code_text(
    name: str,
    qubits: int,
    logical_x: str | None,
    logical_z: str | None,
    stabilizers: list[PauliProduct],
    *,
    distance: int | None = None,
) -> str:
    """Render a one-logical-qubit CSS code or a full-rank stabilizer state."""
    if (logical_x is None) != (logical_z is None):
        raise ValueError("logical X and Z must either both be present or both be absent")
    if logical_x is None:
        if len(stabilizers) != qubits:
            raise ValueError("a stabilizer-state code needs exactly one check per qubit")
        parameters = f"[[{qubits},0]]"
        logical_text: tuple[str, ...] = ()
    else:
        parameters = (
            f"[[{qubits},1,{distance}]]" if distance is not None else f"[[{qubits},1]]"
        )
        logical_text = (f"    LOGICAL {logical_x} {logical_z}",)
    return "\n".join(
        (
            f"CODE {name} {parameters} {{",
            *logical_text,
            f"    STABILIZER {products_text(stabilizers)}",
            "}",
        )
    )
